#!/bin/sh
#
### BEGIN INIT INFO
# Provides: gem-tanzanite
# Required-Start: $local_fs $remote_fs weston
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

case "$1" in
  start)
        . /etc/profile
        /usr/bin/gem-tanzanite &
  ;;

  stop)
        echo "Stopping gem-tanzanite"
        killproc firefox
  ;;

  restart)
	$0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
